apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-manager-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: nginx-manager-watcher
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
