kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-manager-watcher
  namespace: default
subjects:
  - kind: ServiceAccount
    name: nginx-manager-watcher
    namespace: default
roleRef:
  kind: Role
  name: nginx-manager-watcher
  apiGroup: rbac.authorization.k8s.io